basePath: /
definitions:
  params.ReqBankAccountLogin:
    properties:
      account_id:
        type: integer
    type: object
  params.ReqBankOrderPaymentBank:
    properties:
      amount:
        type: number
      bank_account_id:
        type: integer
      card_number:
        type: string
      order_id:
        type: string
      remark:
        type: string
    type: object
  params.ReqBankOrderPaymentQR:
    properties:
      amount:
        type: number
      bank_account_id:
        type: integer
      card_number:
        type: string
      order_id:
        type: string
      remark:
        type: string
    type: object
  params.ReqBankTransferBank:
    properties:
      amount:
        type: number
      bank_account_id:
        type: integer
      card_number:
        type: string
      order_id:
        type: string
      remark:
        type: string
    type: object
host: localhost:7068
info:
  contact: {}
  description: 这是一个管理银行以及银行卡的一体化系统
  termsOfService: http://example.com/terms/
  title: PaymentEngine
  version: "1.0"
paths:
  /api/v1/bank/account/financial/list:
    get:
      consumes:
      - application/json
      description: 获取银行账户资金明细
      parameters:
      - description: 账户 AccountId
        in: query
        name: account_id
        type: integer
      - description: 银行卡号码
        in: query
        name: card_number
        type: string
      - description: 第几页，默认 1
        in: query
        name: page_num
        type: integer
      - description: 每一页显示的数量，默认 10
        in: query
        name: page_size
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 健康状态
          schema: {}
      summary: 银行账户资金明细
      tags:
      - 银行账户
  /api/v1/bank/account/list:
    get:
      consumes:
      - application/json
      description: 银行账户列表
      parameters:
      - description: 账户名称
        in: query
        name: account
        type: string
      - description: 账户 ID
        in: query
        name: id
        type: integer
      - description: 第几页，默认 1
        in: query
        name: page_num
        type: integer
      - description: 每一页显示的数量，默认 10
        in: query
        name: page_size
        type: integer
      - description: 服务提供商名称
        in: query
        name: provider
        type: string
      - description: '状态值，1: 启用，2: 禁用 4: 异常'
        in: query
        name: status
        type: integer
      - collectionFormat: csv
        description: 标签 ID 列表
        in: query
        items:
          type: integer
        name: tag_ids
        type: array
      produces:
      - application/json
      responses:
        "200":
          description: 健康状态
          schema: {}
      summary: 银行账户列表
      tags:
      - 银行账户
  /api/v1/bank/account/login:
    post:
      consumes:
      - application/json
      description: 登录银行账户
      parameters:
      - description: 查询参数
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/params.ReqBankAccountLogin'
      produces:
      - application/json
      responses:
        "200":
          description: 健康状态
          schema: {}
      summary: 登录
      tags:
      - 银行账户
  /api/v1/bank/account/tag/list:
    get:
      consumes:
      - application/json
      description: 银行账户标签列表
      parameters:
      - collectionFormat: csv
        description: 标签 AccountId 列表
        in: query
        items:
          type: integer
        name: ids
        type: array
      - description: 服务提供商名称
        in: query
        name: provider
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 健康状态
          schema: {}
      summary: 银行账户标签列表
      tags:
      - 银行账户
  /api/v1/bank/order/payment/bank:
    post:
      consumes:
      - application/json
      description: 生成收款银行信息
      parameters:
      - description: 提交参数
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/params.ReqBankOrderPaymentBank'
      produces:
      - application/json
      responses:
        "200":
          description: 响应
          schema: {}
      summary: 收款银行信息
      tags:
      - 银行订单
  /api/v1/bank/order/payment/qr:
    post:
      consumes:
      - application/json
      description: 生成收款二维码
      parameters:
      - description: 查询参数
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/params.ReqBankOrderPaymentQR'
      produces:
      - application/json
      responses:
        "200":
          description: 健康状态
          schema: {}
      summary: 收款二维码
      tags:
      - 银行订单
  /api/v1/bank/order/transfer/bank:
    post:
      consumes:
      - application/json
      description: 生成出款银行订单
      parameters:
      - description: 提交参数
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/params.ReqBankTransferBank'
      produces:
      - application/json
      responses:
        "200":
          description: 响应
          schema: {}
      summary: 出款银行订单
      tags:
      - 银行订单
swagger: "2.0"
